language: erlang # wither art thou, Go?

install:
 - hg clone -r weekly https://code.google.com/p/go $HOME/go
 - cd $HOME/go/src && ./make.bash
 - mkdir -p $HOME/src || true
 - mkdir -p $HOME/bin || true
 - mkdir -p $HOME/pkg || true
 - export GOPATH=$HOME
 - export PATH=$PATH:$HOME/go/bin
 - ln -s $HOME/builds/peterbourgon/diskv $HOME/src/diskv
 - go get -v github.com/petar/GoLLRB/llrb

script:
 - cd $HOME/src/diskv && go build -v .
 - cd $HOME/src/diskv && go test -v .

